---
- name: change hostname to match node name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: update /etc/hosts as well
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1\t.*$"
    line: "127.0.1.1\t{{ inventory_hostname }}"

- name: update apt repos
  ansible.builtin.apt:
    update_cache: yes

- name: install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: discover swap status
  ansible.builtin.shell:
    cmd: cat /proc/swaps | wc -l
  register: swap_out

- name: disable swap if enabled
  ansible.builtin.shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    systemctl disable dphys-swapfile
  when: swap_out.stdout != "1"

- name: reboot host
  ansible.builtin.reboot:
  when: swap_out.stdout != "1"
