---
- name: create directory hierarchy
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: "0755"
  loop:
    - "{{ pxe_iso_dir }}"
    - "{{ pxe_boot_dir }}"
    - "{{ pxe_menu_dir }}"

- name: create netboot mode directories
  ansible.builtin.file:
    path: "{{ pxe_base_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ pxe_boot_modes }}"

- name: install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pxe_packages }}"

- name: copy required files for bios
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ pxe_base_dir }}/bios/"
    remote_src: yes
  loop:
    - /usr/lib/syslinux/modules/bios/ldlinux.c32
    - /usr/lib/syslinux/modules/bios/vesamenu.c32
    - /usr/lib/syslinux/modules/bios/libcom32.c32
    - /usr/lib/syslinux/modules/bios/libutil.c32
    - /usr/lib/PXELINUX/pxelinux.0
  when: "'bios' in pxe_boot_modes"

- name: copy required files for efi64
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ pxe_base_dir }}/efi64/"
    remote_src: yes
  loop:
    - /usr/lib/syslinux/modules/efi64/ldlinux.e64
    - /usr/lib/syslinux/modules/efi64/vesamenu.c32
    - /usr/lib/syslinux/modules/efi64/libcom32.c32
    - /usr/lib/syslinux/modules/efi64/libutil.c32
    - /usr/lib/SYSLINUX.EFI/efi64/syslinux.efi
  when: "'efi64' in pxe_boot_modes"

- name: extract all the iso's
  ansible.builtin.include_tasks: extract_iso.yml
  vars:
    pxe_iso: "{{ pxe_iso_dir }}/{{ item.arch }}_{{ item.distro }}_{{ item.version }}_{{ item.variant }}.{{ item.ext | default('iso') }}"
    pxe_iso_fstype: "{{ item.fstype | default('iso9660') }}"
    pxe_copy_src: "{{ pxe_mnt_dir }}/{{ item.arch }}_{{ item.distro }}_{{ item.version }}_{{ item.variant }}"
    pxe_copy_dst: "{{ pxe_boot_dir }}/{{ item.arch }}/{{ item.distro }}/{{ item.version }}/{{ item.variant }}"
  loop: "{{ pxe_hosting }}"
  when: "not item.copied | default(false)"

- name: create pxelinux default menu
  ansible.builtin.template:
    src: templates/default.j2
    dest: "{{ pxe_menu_dir }}/default"
    
