---
- name: create target
  ansible.builtin.file:
    path: "{{ usb_storage_target }}"
    state: directory
    mode: "0755"
  when: usb_storage_target is defined

- name: mount usb storage via uuid
  ansible.posix.mount:
    path: "{{ usb_storage_target }}"
    src: "UUID={{ usb_storage_uuid }}"
    fstype: "{{ usb_stoage_fstype | default('ext4') }}"
    opts: noatime
    state: present
  when: usb_storage_target is defined and usb_storage_uuid is defined
